id: P001718
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:16:26.619888
source_metadata:
  id: bdr:W1KG3866
  title: ཐེག་པ་མཐའ་དག་གི་སྙིང་པོ་མདོ་ཙམ་བརྗོད་པ་ཆོས་ཀྱི་སྒོ་འབྱེད་
  author: ''
  volumes:
    80ab64268dac4f619e666fd3f06d0c6e:
      image_group_id: I1KG3942
      title: ''
      volume_number: 1
      total_pages: 20
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
