id: I859A7D0A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T11:04:44+00:00'
last_modified: '2022-06-07T14:11:44.371525+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3866
  title: ཐེག་པ་མཐའ་དག་གི་སྙིང་པོ་མདོ་ཙམ་བརྗོད་པ་ཆོས་ཀྱི་སྒོ་འབྱེད་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1F64:
      image_group_id: I1KG3942
      title: ''
      total_pages: 20
      order: 1
      base_file: 1F64.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
