id: I859A7D0A
legacy_id: P001718
ocr_import_info:
  bdrc_scan_id: W1KG3866
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T11:04:37'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:18:02.193386+00:00'
last_modified: 2022-08-31 23:18:06.562214
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3866
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3866
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐེག་པ་མཐའ་དག་གི་སྙིང་པོ་མདོ་ཙམ་བརྗོད་པ་ཆོས་ཀྱི་སྒོ་འབྱེད།
  author: རྫོང་གསར་མཁྱེན་བརྩེ ༠༢་འཇམ་དབྱངས་ཆོས་ཀྱི་བློ་གྲོས།
statistics:
  ocr_word_mean_confidence_index: 0.6080329989710476
  ocr_word_median_confidence_index: 0.6700000166893005
quality: null
bases:
  I1KG3942:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3942
      total_pages: 20
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3942.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6080329989710476
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
